# frozen_string_literal: true

RSpec.shared_context 'sugar account and contacts', shared_context: :metadata do
  let(:account_hbx_id) { '1000610' }
  let(:spouse_hbx_id) { '1000643' }
  let(:child1_hbx_id) { '1000644' }
  let(:child2_hbx_id) { '1000645' }
  let(:child3_hbx_id) { '1000646' }
  let(:child4_hbx_id) { '1000647' }
  let(:child5_hbx_id) { '1000648' }

  let(:sugar_contacts) do
    [
      { :id => "cdf794d4-2c39-11ec-b5d2-06605441e25d",
        :name => "Jane Doe",
        :date_entered => "2021-10-13T15:25:32+00:00",
        :date_modified => "2024-07-02T17:47:54+00:00",
        :modified_user_id => "75166564-1c91-11ec-83e9-36c3beb387af",
        :modified_by_name => "Enroll API",
        :modified_user_link =>
     { :full_name => "Enroll API",
       :id => "75166564-1c91-11ec-83e9-36c3beb387af",
       :_acl =>
       { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
         :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
        :created_by => "75166564-1c91-11ec-83e9-36c3beb387af",
        :created_by_name => "Enroll API",
        :created_by_link =>
     { :full_name => "Enroll API",
       :id => "75166564-1c91-11ec-83e9-36c3beb387af",
       :_acl =>
       { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
         :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
        :description => "",
        :deleted => false,
        :salutation => "",
        :first_name => "Jane",
        :last_name => "Doe",
        :full_name => "Jane Doe",
        :title => "",
        :facebook => "",
        :twitter => "",
        :googleplus => "",
        :department => "",
        :do_not_call => false,
        :phone_home => "",
        :phone_mobile => "(999) 123-1234",
        :phone_work => "",
        :phone_other => "",
        :phone_fax => "",
        :primary_address_street => "",
        :primary_address_street_2 => "",
        :primary_address_street_3 => "",
        :primary_address_city => "",
        :primary_address_state => "",
        :primary_address_postalcode => "",
        :primary_address_country => "",
        :alt_address_street => "",
        :alt_address_street_2 => "",
        :alt_address_street_3 => "",
        :alt_address_city => "",
        :alt_address_state => "",
        :alt_address_postalcode => "",
        :alt_address_country => "",
        :assistant => "",
        :assistant_phone => "",
        :picture => "",
        :email_and_name1 => "",
        :lead_source => "",
        :account_name => "Jane Test Doe",
        :accounts => { :name => "Jane Test Doe", :id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
                       :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :account_id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
        :dnb_principal_id => "",
        :opportunity_role_fields => "",
        :opportunities => { :id => "" },
        :opportunity_role_id => "",
        :opportunity_role => "",
        :reports_to_id => "",
        :report_to_name => "",
        :reports_to_link => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :birthdate => "1990-01-01",
        :portal_name => "",
        :portal_active => false,
        :portal_password => nil,
        :portal_password1 => nil,
        :portal_app => "",
        :portal_user_company_name => "",
        :preferred_language => "",
        :cookie_consent => false,
        :cookie_consent_received_on => "",
        :business_center_name => "",
        :business_centers =>
     { :name => "",
       :id => "",
       :_acl =>
       { :fields => [],
         :access => "no",
         :view => "no",
         :list => "no",
         :edit => "no",
         :delete => "no",
         :import => "no",
         :export => "no",
         :massupdate => "no",
         :_hash => "3fd204ac1b6d951752c529c51f978bc3" } },
        :business_center_id => "",
        :dp_business_purpose => [],
        :dp_consent_last_updated => "2021-10-13",
        :campaign_id => "",
        :campaign_name => "",
        :campaign_contacts => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :c_accept_status_fields => "",
        :calls => { :id => "" },
        :m_accept_status_fields => "",
        :meetings => { :id => "" },
        :accept_status_id => "",
        :accept_status_name => "",
        :accept_status_calls => "",
        :accept_status_meetings => "",
        :sync_contact => false,
        :mkto_sync => false,
        :mkto_id => nil,
        :mkto_lead_score => nil,
        :entry_source => "internal",
        :site_user_id => "",
        :following => true,
        :my_favorite => false,
        :tag => [],
        :locked_fields => [],
        :assigned_user_id => "",
        :assigned_user_name => "",
        :assigned_user_link => { :full_name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :team_count => "",
        :team_count_link => { :team_count => "", :id => "1", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :team_name => [{ :id => "1", :name => "Global", :name_2 => "", :primary => true, :selected => false }],
        :email =>
     [{ :email_address => "JaneDoe@gmail.com",
        :primary_address => true,
        :reply_to_address => false,
        :invalid_email => false,
        :opt_out => false,
        :email_address_id => "184f7114-20af-11ec-a650-36c3beb387af" }],
        :email1 => "JaneDoe@gmail.com",
        :email2 => "",
        :invalid_email => false,
        :email_opt_out => false,
        :email_addresses_non_primary => "",
        :hbxid_c => "1000610",
        :relationship_c => "Self",
        :gender_c => "male",
        :_acl => { :fields => {} },
        :_module => "Contacts" },
      { :id => "070e9ef8-3e72-11ec-9c29-0ec9dd084159",
        :name => "John Doe",
        :date_entered => "2021-11-05T19:53:20+00:00",
        :date_modified => "2023-10-23T19:41:01+00:00",
        :modified_user_id => "75166564-1c91-11ec-83e9-36c3beb387af",
        :modified_by_name => "Enroll API",
        :modified_user_link =>
        { :full_name => "Enroll API",
          :id => "75166564-1c91-11ec-83e9-36c3beb387af",
          :_acl =>
          { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
            :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
        :created_by => "75166564-1c91-11ec-83e9-36c3beb387af",
        :created_by_name => "Enroll API",
        :created_by_link =>
        { :full_name => "Enroll API",
          :id => "75166564-1c91-11ec-83e9-36c3beb387af",
          :_acl =>
          { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
            :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
        :description => "",
        :deleted => false,
        :salutation => "",
        :first_name => "John",
        :last_name => "Doe",
        :full_name => "John Doe",
        :title => "",
        :facebook => "",
        :twitter => "",
        :googleplus => "",
        :department => "",
        :do_not_call => false,
        :phone_home => "",
        :phone_mobile => "",
        :phone_work => "",
        :phone_other => "",
        :phone_fax => "",
        :primary_address_street => "",
        :primary_address_street_2 => "",
        :primary_address_street_3 => "",
        :primary_address_city => "",
        :primary_address_state => "",
        :primary_address_postalcode => "",
        :primary_address_country => "",
        :alt_address_street => "",
        :alt_address_street_2 => "",
        :alt_address_street_3 => "",
        :alt_address_city => "",
        :alt_address_state => "",
        :alt_address_postalcode => "",
        :alt_address_country => "",
        :assistant => "",
        :assistant_phone => "",
        :picture => "",
        :email_and_name1 => "",
        :lead_source => "",
        :account_name => "Jane Test Doe",
        :accounts => { :name => "Jane Test Doe", :id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
                       :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :account_id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
        :dnb_principal_id => "",
        :opportunity_role_fields => "",
        :opportunities => { :id => "" },
        :opportunity_role_id => "",
        :opportunity_role => "",
        :reports_to_id => "",
        :report_to_name => "",
        :reports_to_link => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :birthdate => "1990-01-02",
        :portal_name => "",
        :portal_active => false,
        :portal_password => nil,
        :portal_password1 => nil,
        :portal_app => "",
        :portal_user_company_name => "",
        :preferred_language => "",
        :cookie_consent => false,
        :cookie_consent_received_on => "",
        :business_center_name => "",
        :business_centers =>
        { :name => "",
          :id => "",
          :_acl =>
          { :fields => [],
            :access => "no",
            :view => "no",
            :list => "no",
            :edit => "no",
            :delete => "no",
            :import => "no",
            :export => "no",
            :massupdate => "no",
            :_hash => "3fd204ac1b6d951752c529c51f978bc3" } },
        :business_center_id => "",
        :dp_business_purpose => [],
        :dp_consent_last_updated => "2021-11-05",
        :campaign_id => "",
        :campaign_name => "",
        :campaign_contacts => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :c_accept_status_fields => "",
        :calls => { :id => "" },
        :m_accept_status_fields => "",
        :meetings => { :id => "" },
        :accept_status_id => "",
        :accept_status_name => "",
        :accept_status_calls => "",
        :accept_status_meetings => "",
        :sync_contact => false,
        :mkto_sync => false,
        :mkto_id => nil,
        :mkto_lead_score => nil,
        :entry_source => "internal",
        :site_user_id => "",
        :following => true,
        :my_favorite => false,
        :tag => [],
        :locked_fields => [],
        :assigned_user_id => "",
        :assigned_user_name => "",
        :assigned_user_link => { :full_name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :team_count => "",
        :team_count_link => { :team_count => "", :id => "1", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :team_name => [{ :id => "1", :name => "Global", :name_2 => "", :primary => true, :selected => false }],
        :email => [],
        :email1 => "",
        :email2 => "",
        :invalid_email => "",
        :email_opt_out => "",
        :email_addresses_non_primary => "",
        :hbxid_c => spouse_hbx_id,
        :relationship_c => "Spouse",
        :gender_c => "male",
        :_acl => { :fields => {} },
        :_module => "Contacts" },
      { :id => "06a6c602-3e72-11ec-b3cb-0ec9dd084159",
        :name => "Child1 Testing",
        :date_entered => "2021-11-05T19:53:19+00:00",
        :date_modified => "2023-10-23T19:41:00+00:00",
        :modified_user_id => "75166564-1c91-11ec-83e9-36c3beb387af",
        :modified_by_name => "Enroll API",
        :modified_user_link =>
        { :full_name => "Enroll API",
          :id => "75166564-1c91-11ec-83e9-36c3beb387af",
          :_acl =>
          { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
            :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
        :created_by => "75166564-1c91-11ec-83e9-36c3beb387af",
        :created_by_name => "Enroll API",
        :created_by_link =>
        { :full_name => "Enroll API",
          :id => "75166564-1c91-11ec-83e9-36c3beb387af",
          :_acl =>
          { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
            :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
        :description => "",
        :deleted => false,
        :salutation => "",
        :first_name => "Child1",
        :last_name => "Testing",
        :full_name => "Child1 Testing",
        :title => "",
        :facebook => "",
        :twitter => "",
        :googleplus => "",
        :department => "",
        :do_not_call => false,
        :phone_home => "",
        :phone_mobile => "",
        :phone_work => "",
        :phone_other => "",
        :phone_fax => "",
        :primary_address_street => "",
        :primary_address_street_2 => "",
        :primary_address_street_3 => "",
        :primary_address_city => "",
        :primary_address_state => "",
        :primary_address_postalcode => "",
        :primary_address_country => "",
        :alt_address_street => "",
        :alt_address_street_2 => "",
        :alt_address_street_3 => "",
        :alt_address_city => "",
        :alt_address_state => "",
        :alt_address_postalcode => "",
        :alt_address_country => "",
        :assistant => "",
        :assistant_phone => "",
        :picture => "",
        :email_and_name1 => "",
        :lead_source => "",
        :account_name => "Jane Test Doe",
        :accounts => { :name => "Jane Test Doe", :id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
                       :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :account_id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
        :dnb_principal_id => "",
        :opportunity_role_fields => "",
        :opportunities => { :id => "" },
        :opportunity_role_id => "",
        :opportunity_role => "",
        :reports_to_id => "",
        :report_to_name => "",
        :reports_to_link => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :birthdate => "2003-01-01",
        :portal_name => "",
        :portal_active => false,
        :portal_password => nil,
        :portal_password1 => nil,
        :portal_app => "",
        :portal_user_company_name => "",
        :preferred_language => "",
        :cookie_consent => false,
        :cookie_consent_received_on => "",
        :business_center_name => "",
        :business_centers =>
        { :name => "",
          :id => "",
          :_acl =>
          { :fields => [],
            :access => "no",
            :view => "no",
            :list => "no",
            :edit => "no",
            :delete => "no",
            :import => "no",
            :export => "no",
            :massupdate => "no",
            :_hash => "3fd204ac1b6d951752c529c51f978bc3" } },
        :business_center_id => "",
        :dp_business_purpose => [],
        :dp_consent_last_updated => "2021-11-05",
        :campaign_id => "",
        :campaign_name => "",
        :campaign_contacts => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :c_accept_status_fields => "",
        :calls => { :id => "" },
        :m_accept_status_fields => "",
        :meetings => { :id => "" },
        :accept_status_id => "",
        :accept_status_name => "",
        :accept_status_calls => "",
        :accept_status_meetings => "",
        :sync_contact => false,
        :mkto_sync => false,
        :mkto_id => nil,
        :mkto_lead_score => nil,
        :entry_source => "internal",
        :site_user_id => "",
        :following => true,
        :my_favorite => false,
        :tag => [],
        :locked_fields => [],
        :assigned_user_id => "",
        :assigned_user_name => "",
        :assigned_user_link => { :full_name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :team_count => "",
        :team_count_link => { :team_count => "", :id => "1", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :team_name => [{ :id => "1", :name => "Global", :name_2 => "", :primary => true, :selected => false }],
        :email => [],
        :email1 => "",
        :email2 => "",
        :invalid_email => "",
        :email_opt_out => "",
        :email_addresses_non_primary => "",
        :hbxid_c => child1_hbx_id,
        :relationship_c => "Child",
        :gender_c => "male",
        :_acl => { :fields => {} },
        :_module => "Contacts" },
      { :id => "063d7a9e-3e72-11ec-a6e6-0ec9dd084159",
        :name => "Child2 Testing",
        :date_entered => "2021-11-05T19:53:19+00:00",
        :date_modified => "2023-10-23T19:40:59+00:00",
        :modified_user_id => "75166564-1c91-11ec-83e9-36c3beb387af",
        :modified_by_name => "Enroll API",
        :modified_user_link =>
        { :full_name => "Enroll API",
          :id => "75166564-1c91-11ec-83e9-36c3beb387af",
          :_acl =>
          { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
            :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
        :created_by => "75166564-1c91-11ec-83e9-36c3beb387af",
        :created_by_name => "Enroll API",
        :created_by_link =>
        { :full_name => "Enroll API",
          :id => "75166564-1c91-11ec-83e9-36c3beb387af",
          :_acl =>
          { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
            :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
        :description => "",
        :deleted => false,
        :salutation => "",
        :first_name => "Child2",
        :last_name => "Testing",
        :full_name => "Child2 Testing",
        :title => "",
        :facebook => "",
        :twitter => "",
        :googleplus => "",
        :department => "",
        :do_not_call => false,
        :phone_home => "",
        :phone_mobile => "",
        :phone_work => "",
        :phone_other => "",
        :phone_fax => "",
        :primary_address_street => "",
        :primary_address_street_2 => "",
        :primary_address_street_3 => "",
        :primary_address_city => "",
        :primary_address_state => "",
        :primary_address_postalcode => "",
        :primary_address_country => "",
        :alt_address_street => "",
        :alt_address_street_2 => "",
        :alt_address_street_3 => "",
        :alt_address_city => "",
        :alt_address_state => "",
        :alt_address_postalcode => "",
        :alt_address_country => "",
        :assistant => "",
        :assistant_phone => "",
        :picture => "",
        :email_and_name1 => "",
        :lead_source => "",
        :account_name => "Jane Test Doe",
        :accounts => { :name => "Jane Test Doe", :id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
                       :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :account_id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
        :dnb_principal_id => "",
        :opportunity_role_fields => "",
        :opportunities => { :id => "" },
        :opportunity_role_id => "",
        :opportunity_role => "",
        :reports_to_id => "",
        :report_to_name => "",
        :reports_to_link => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :birthdate => "2005-01-01",
        :portal_name => "",
        :portal_active => false,
        :portal_password => nil,
        :portal_password1 => nil,
        :portal_app => "",
        :portal_user_company_name => "",
        :preferred_language => "",
        :cookie_consent => false,
        :cookie_consent_received_on => "",
        :business_center_name => "",
        :business_centers =>
        { :name => "",
          :id => "",
          :_acl =>
          { :fields => [],
            :access => "no",
            :view => "no",
            :list => "no",
            :edit => "no",
            :delete => "no",
            :import => "no",
            :export => "no",
            :massupdate => "no",
            :_hash => "3fd204ac1b6d951752c529c51f978bc3" } },
        :business_center_id => "",
        :dp_business_purpose => [],
        :dp_consent_last_updated => "2021-11-05",
        :campaign_id => "",
        :campaign_name => "",
        :campaign_contacts => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :c_accept_status_fields => "",
        :calls => { :id => "" },
        :m_accept_status_fields => "",
        :meetings => { :id => "" },
        :accept_status_id => "",
        :accept_status_name => "",
        :accept_status_calls => "",
        :accept_status_meetings => "",
        :sync_contact => false,
        :mkto_sync => false,
        :mkto_id => nil,
        :mkto_lead_score => nil,
        :entry_source => "internal",
        :site_user_id => "",
        :following => true,
        :my_favorite => false,
        :tag => [],
        :locked_fields => [],
        :assigned_user_id => "",
        :assigned_user_name => "",
        :assigned_user_link => { :full_name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :team_count => "",
        :team_count_link => { :team_count => "", :id => "1", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :team_name => [{ :id => "1", :name => "Global", :name_2 => "", :primary => true, :selected => false }],
        :email => [],
        :email1 => "",
        :email2 => "",
        :invalid_email => "",
        :email_opt_out => "",
        :email_addresses_non_primary => "",
        :hbxid_c => child2_hbx_id,
        :relationship_c => "Child",
        :gender_c => "male",
        :_acl => { :fields => {} },
        :_module => "Contacts" },
      { :id => "05d3e0ac-3e72-11ec-a38f-0ec9dd084159",
        :name => "Child3 Doe",
        :date_entered => "2021-11-05T19:53:18+00:00",
        :date_modified => "2023-10-23T19:40:59+00:00",
        :modified_user_id => "75166564-1c91-11ec-83e9-36c3beb387af",
        :modified_by_name => "Enroll API",
        :modified_user_link =>
        { :full_name => "Enroll API",
          :id => "75166564-1c91-11ec-83e9-36c3beb387af",
          :_acl =>
          { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
            :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
        :created_by => "75166564-1c91-11ec-83e9-36c3beb387af",
        :created_by_name => "Enroll API",
        :created_by_link =>
        { :full_name => "Enroll API",
          :id => "75166564-1c91-11ec-83e9-36c3beb387af",
          :_acl =>
          { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
            :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
        :description => "",
        :deleted => false,
        :salutation => "",
        :first_name => "Child3",
        :last_name => "Doe",
        :full_name => "Child3 Doe",
        :title => "",
        :facebook => "",
        :twitter => "",
        :googleplus => "",
        :department => "",
        :do_not_call => false,
        :phone_home => "",
        :phone_mobile => "",
        :phone_work => "",
        :phone_other => "",
        :phone_fax => "",
        :primary_address_street => "",
        :primary_address_street_2 => "",
        :primary_address_street_3 => "",
        :primary_address_city => "",
        :primary_address_state => "",
        :primary_address_postalcode => "",
        :primary_address_country => "",
        :alt_address_street => "",
        :alt_address_street_2 => "",
        :alt_address_street_3 => "",
        :alt_address_city => "",
        :alt_address_state => "",
        :alt_address_postalcode => "",
        :alt_address_country => "",
        :assistant => "",
        :assistant_phone => "",
        :picture => "",
        :email_and_name1 => "",
        :lead_source => "",
        :account_name => "Jane Test Doe",
        :accounts => { :name => "Jane Test Doe", :id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
                       :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :account_id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
        :dnb_principal_id => "",
        :opportunity_role_fields => "",
        :opportunities => { :id => "" },
        :opportunity_role_id => "",
        :opportunity_role => "",
        :reports_to_id => "",
        :report_to_name => "",
        :reports_to_link => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :birthdate => "2017-01-01",
        :portal_name => "",
        :portal_active => false,
        :portal_password => nil,
        :portal_password1 => nil,
        :portal_app => "",
        :portal_user_company_name => "",
        :preferred_language => "",
        :cookie_consent => false,
        :cookie_consent_received_on => "",
        :business_center_name => "",
        :business_centers =>
        { :name => "",
          :id => "",
          :_acl =>
          { :fields => [],
            :access => "no",
            :view => "no",
            :list => "no",
            :edit => "no",
            :delete => "no",
            :import => "no",
            :export => "no",
            :massupdate => "no",
            :_hash => "3fd204ac1b6d951752c529c51f978bc3" } },
        :business_center_id => "",
        :dp_business_purpose => [],
        :dp_consent_last_updated => "2021-11-05",
        :campaign_id => "",
        :campaign_name => "",
        :campaign_contacts => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :c_accept_status_fields => "",
        :calls => { :id => "" },
        :m_accept_status_fields => "",
        :meetings => { :id => "" },
        :accept_status_id => "",
        :accept_status_name => "",
        :accept_status_calls => "",
        :accept_status_meetings => "",
        :sync_contact => false,
        :mkto_sync => false,
        :mkto_id => nil,
        :mkto_lead_score => nil,
        :entry_source => "internal",
        :site_user_id => "",
        :following => true,
        :my_favorite => false,
        :tag => [],
        :locked_fields => [],
        :assigned_user_id => "",
        :assigned_user_name => "",
        :assigned_user_link => { :full_name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :team_count => "",
        :team_count_link => { :team_count => "", :id => "1", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :team_name => [{ :id => "1", :name => "Global", :name_2 => "", :primary => true, :selected => false }],
        :email => [],
        :email1 => "",
        :email2 => "",
        :invalid_email => "",
        :email_opt_out => "",
        :email_addresses_non_primary => "",
        :hbxid_c => child3_hbx_id,
        :relationship_c => "Child",
        :gender_c => "male",
        :_acl => { :fields => {} },
        :_module => "Contacts" },
      { :id => "6769a650-44b9-11ed-b410-ea888cdf0920",
        :name => "Nineteen Test",
        :date_entered => "2022-10-05T14:24:21+00:00",
        :date_modified => "2022-10-05T14:25:06+00:00",
        :modified_user_id => "75166564-1c91-11ec-83e9-36c3beb387af",
        :modified_by_name => "Enroll API",
        :modified_user_link =>
        { :full_name => "Enroll API",
          :id => "75166564-1c91-11ec-83e9-36c3beb387af",
          :_acl =>
          { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
            :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
        :created_by => "75166564-1c91-11ec-83e9-36c3beb387af",
        :created_by_name => "Enroll API",
        :created_by_link =>
        { :full_name => "Enroll API",
          :id => "75166564-1c91-11ec-83e9-36c3beb387af",
          :_acl =>
          { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
            :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
        :description => "",
        :deleted => false,
        :salutation => "",
        :first_name => "Nineteen",
        :last_name => "Test",
        :full_name => "Nineteen Test",
        :title => "",
        :facebook => "",
        :twitter => "",
        :googleplus => "",
        :department => "",
        :do_not_call => false,
        :phone_home => "",
        :phone_mobile => "",
        :phone_work => "",
        :phone_other => "",
        :phone_fax => "",
        :primary_address_street => "",
        :primary_address_street_2 => "",
        :primary_address_street_3 => "",
        :primary_address_city => "",
        :primary_address_state => "",
        :primary_address_postalcode => "",
        :primary_address_country => "",
        :alt_address_street => "",
        :alt_address_street_2 => "",
        :alt_address_street_3 => "",
        :alt_address_city => "",
        :alt_address_state => "",
        :alt_address_postalcode => "",
        :alt_address_country => "",
        :assistant => "",
        :assistant_phone => "",
        :picture => "",
        :email_and_name1 => "",
        :lead_source => "",
        :account_name => "Jane Test Doe",
        :accounts => { :name => "Jane Test Doe", :id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
                       :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :account_id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
        :dnb_principal_id => "",
        :opportunity_role_fields => "",
        :opportunities => { :id => "" },
        :opportunity_role_id => "",
        :opportunity_role => "",
        :reports_to_id => "",
        :report_to_name => "",
        :reports_to_link => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :birthdate => "2003-01-01",
        :portal_name => "",
        :portal_active => false,
        :portal_password => nil,
        :portal_password1 => nil,
        :portal_app => "",
        :portal_user_company_name => "",
        :preferred_language => "",
        :cookie_consent => false,
        :cookie_consent_received_on => "",
        :business_center_name => "",
        :business_centers =>
        { :name => "",
          :id => "",
          :_acl =>
          { :fields => [],
            :access => "no",
            :view => "no",
            :list => "no",
            :edit => "no",
            :delete => "no",
            :import => "no",
            :export => "no",
            :massupdate => "no",
            :_hash => "3fd204ac1b6d951752c529c51f978bc3" } },
        :business_center_id => "",
        :dp_business_purpose => [],
        :dp_consent_last_updated => "2022-10-05",
        :campaign_id => "",
        :campaign_name => "",
        :campaign_contacts => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :c_accept_status_fields => "",
        :calls => { :id => "" },
        :m_accept_status_fields => "",
        :meetings => { :id => "" },
        :accept_status_id => "",
        :accept_status_name => "",
        :accept_status_calls => "",
        :accept_status_meetings => "",
        :sync_contact => false,
        :mkto_sync => false,
        :mkto_id => nil,
        :mkto_lead_score => nil,
        :entry_source => "internal",
        :site_user_id => "",
        :following => true,
        :my_favorite => false,
        :tag => [],
        :locked_fields => [],
        :assigned_user_id => "",
        :assigned_user_name => "",
        :assigned_user_link => { :full_name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :team_count => "",
        :team_count_link => { :team_count => "", :id => "1", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :team_name => [{ :id => "1", :name => "Global", :name_2 => "", :primary => true, :selected => false }],
        :email => [],
        :email1 => "",
        :email2 => "",
        :invalid_email => "",
        :email_opt_out => "",
        :email_addresses_non_primary => "",
        :hbxid_c => child4_hbx_id,
        :relationship_c => "Child",
        :gender_c => "male",
        :_acl => { :fields => {} },
        :_module => "Contacts" },
      { :id => "9718ef3c-41a8-11ed-b62a-760d8d9fea93",
        :name => "Test Baby",
        :date_entered => "2022-10-01T16:46:26+00:00",
        :date_modified => "2022-10-01T16:46:54+00:00",
        :modified_user_id => "75166564-1c91-11ec-83e9-36c3beb387af",
        :modified_by_name => "Enroll API",
        :modified_user_link =>
        { :full_name => "Enroll API",
          :id => "75166564-1c91-11ec-83e9-36c3beb387af",
          :_acl =>
          { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
            :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
        :created_by => "75166564-1c91-11ec-83e9-36c3beb387af",
        :created_by_name => "Enroll API",
        :created_by_link =>
        { :full_name => "Enroll API",
          :id => "75166564-1c91-11ec-83e9-36c3beb387af",
          :_acl =>
          { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
            :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
        :description => "",
        :deleted => false,
        :salutation => "",
        :first_name => "Test",
        :last_name => "Baby",
        :full_name => "Test Baby",
        :title => "",
        :facebook => "",
        :twitter => "",
        :googleplus => "",
        :department => "",
        :do_not_call => false,
        :phone_home => "",
        :phone_mobile => "",
        :phone_work => "",
        :phone_other => "",
        :phone_fax => "",
        :primary_address_street => "",
        :primary_address_street_2 => "",
        :primary_address_street_3 => "",
        :primary_address_city => "",
        :primary_address_state => "",
        :primary_address_postalcode => "",
        :primary_address_country => "",
        :alt_address_street => "",
        :alt_address_street_2 => "",
        :alt_address_street_3 => "",
        :alt_address_city => "",
        :alt_address_state => "",
        :alt_address_postalcode => "",
        :alt_address_country => "",
        :assistant => "",
        :assistant_phone => "",
        :picture => "",
        :email_and_name1 => "",
        :lead_source => "",
        :account_name => "Jane Test Doe",
        :accounts => { :name => "Jane Test Doe", :id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
                       :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :account_id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
        :dnb_principal_id => "",
        :opportunity_role_fields => "",
        :opportunities => { :id => "" },
        :opportunity_role_id => "",
        :opportunity_role => "",
        :reports_to_id => "",
        :report_to_name => "",
        :reports_to_link => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :birthdate => "2019-10-16",
        :portal_name => "",
        :portal_active => false,
        :portal_password => nil,
        :portal_password1 => nil,
        :portal_app => "",
        :portal_user_company_name => "",
        :preferred_language => "",
        :cookie_consent => false,
        :cookie_consent_received_on => "",
        :business_center_name => "",
        :business_centers =>
        { :name => "",
          :id => "",
          :_acl =>
          { :fields => [],
            :access => "no",
            :view => "no",
            :list => "no",
            :edit => "no",
            :delete => "no",
            :import => "no",
            :export => "no",
            :massupdate => "no",
            :_hash => "3fd204ac1b6d951752c529c51f978bc3" } },
        :business_center_id => "",
        :dp_business_purpose => [],
        :dp_consent_last_updated => "2022-10-01",
        :campaign_id => "",
        :campaign_name => "",
        :campaign_contacts => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :c_accept_status_fields => "",
        :calls => { :id => "" },
        :m_accept_status_fields => "",
        :meetings => { :id => "" },
        :accept_status_id => "",
        :accept_status_name => "",
        :accept_status_calls => "",
        :accept_status_meetings => "",
        :sync_contact => false,
        :mkto_sync => false,
        :mkto_id => nil,
        :mkto_lead_score => nil,
        :entry_source => "internal",
        :site_user_id => "",
        :following => true,
        :my_favorite => false,
        :tag => [],
        :locked_fields => [],
        :assigned_user_id => "",
        :assigned_user_name => "",
        :assigned_user_link => { :full_name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :team_count => "",
        :team_count_link => { :team_count => "", :id => "1", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
        :team_name => [{ :id => "1", :name => "Global", :name_2 => "", :primary => true, :selected => false }],
        :email => [],
        :email1 => "",
        :email2 => "",
        :invalid_email => "",
        :email_opt_out => "",
        :email_addresses_non_primary => "",
        :hbxid_c => child5_hbx_id,
        :relationship_c => "Child",
        :gender_c => "male",
        :_acl => { :fields => {} },
        :_module => "Contacts" }
    ]
  end

  let(:sugar_account) do
    {
      :id => "cd9ddce6-2c39-11ec-9752-06605441e25d",
      :name => "Jane Test Doe",
      :date_entered => "2021-10-13T15:25:31+00:00",
      :date_modified => "2024-07-02T17:47:54+00:00",
      :modified_user_id => "75166564-1c91-11ec-83e9-36c3beb387af",
      :modified_by_name => "Enroll API",
      :modified_user_link =>
      { :full_name => "Enroll API",
        :id => "75166564-1c91-11ec-83e9-36c3beb387af",
        :_acl =>
        { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
          :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
      :created_by => "75166564-1c91-11ec-83e9-36c3beb387af",
      :created_by_name => "Enroll API",
      :created_by_link =>
      { :full_name => "Enroll API",
        :id => "75166564-1c91-11ec-83e9-36c3beb387af",
        :_acl =>
        { :fields => { :pwd_last_changed => { :write => "no", :create => "no" }, :last_login => { :write => "no", :create => "no" } },
          :_hash => "6d408abe1708e7afd72eaecf780699c2" } },
      :description => "",
      :deleted => false,
      :facebook => "",
      :twitter => "",
      :googleplus => "",
      :account_type => "",
      :industry => "",
      :annual_revenue => "",
      :phone_fax => "",
      :billing_address_street => "1 Test St",
      :billing_address_street_2 => "",
      :billing_address_street_3 => "",
      :billing_address_street_4 => "",
      :billing_address_city => "Testing City",
      :billing_address_state => "ME",
      :billing_address_postalcode => "04055",
      :billing_address_country => "",
      :rating => "",
      :phone_office => "(999) 123-1234",
      :phone_alternate => "",
      :website => "",
      :ownership => "",
      :employees => "",
      :ticker_symbol => "",
      :shipping_address_street => "",
      :shipping_address_street_2 => "",
      :shipping_address_street_3 => "",
      :shipping_address_street_4 => "",
      :shipping_address_city => "",
      :shipping_address_state => "",
      :shipping_address_postalcode => "",
      :shipping_address_country => "",
      :service_level => "",
      :parent_id => "",
      :sic_code => "",
      :duns_num => "",
      :parent_name => "",
      :member_of => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
      :campaign_id => "",
      :campaign_name => "",
      :campaign_accounts => { :name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
      :next_renewal_date => "",
      :following => true,
      :my_favorite => false,
      :tag => [],
      :locked_fields => [],
      :assigned_user_id => "",
      :assigned_user_name => "",
      :assigned_user_link => { :full_name => "", :id => "", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
      :team_count => "",
      :team_count_link => { :team_count => "", :id => "1", :_acl => { :fields => [], :_hash => "654d337e0e912edaa00dbb0fb3dc3c17" } },
      :team_name => [{ :id => "1", :name => "Global", :name_2 => "", :primary => true, :selected => false }],
      :email =>
      [{ :email_address => "JaneDoe@gmail.com",
         :primary_address => true,
         :reply_to_address => false,
         :invalid_email => false,
         :opt_out => false,
         :email_address_id => "184f7114-20af-11ec-a650-36c3beb387af" }],
      :email1 => "JaneDoe@gmail.com",
      :email2 => "",
      :invalid_email => false,
      :email_opt_out => false,
      :email_addresses_non_primary => "",
      :hbxid_c => account_hbx_id,
      :enroll_account_link_c => "http://test-enroll.testing/exchanges/agents/resume_enrollment?person_id=6156ad3ee42dcb01818667af",
      :next_best_action_c => "",
      :opt_out_of_emails_c => false,
      :raw_ssn_c => "111111111",
      :broker_c => "",
      :ssn_c => "XXX-XX-1111",
      :last_ea_action_at_c => "",
      :dob_c => "1990-01-01",
      :last_ea_action_c => "",
      :_acl => { :fields => {} },
      :_module => "Accounts"
    }
  end

  let(:input_params) do
    sugar_account.merge({ contacts: sugar_contacts })
  end

  let(:cv3_family) do
    { :hbx_id => "171686263144070",
      :family_members =>
      [{ :hbx_id => "732020",
         :is_primary_applicant => true,
         :is_consent_applicant => false,
         :is_coverage_applicant => true,
         :is_active => true,
         :person =>
        { :person_id => "66553ea76e3a72323152ccd4",
          :external_person_link => "http://127.0.0.1:3000/exchanges/agents/resume_enrollment?person_id=66553ea76e3a72323152ccd4",
          :hbx_id => "732020",
          :person_name => { :first_name => "John", :middle_name => nil, :last_name => "Smith1",
                            :name_sfx => nil, :name_pfx => nil, :full_name => "John Smith1",
                            :alternate_name => nil },
          :person_demographics =>
          { :encrypted_ssn => "cb6H09SJ4Fhd3sNr0MAOVYYHuP8BKMdKlQ==\n",
            :no_ssn => false,
            :gender => "male",
            :dob => Time.zone.today,
            :date_of_death => nil,
            :dob_check => nil,
            :is_incarcerated => false,
            :ethnicity => nil,
            :race => nil,
            :tribal_id => nil,
            :language_code => "en",
            :alive_status => {} },
          :person_health => { :is_physically_disabled => nil, :is_tobacco_user => "unknown" },
          :no_dc_address => false,
          :no_dc_address_reason => "",
          :is_homeless => false,
          :is_temporarily_out_of_state => false,
          :age_off_excluded => false,
          :is_applying_for_assistance => nil,
          :is_active => true,
          :is_disabled => nil,
          :person_relationships => [],
          :consumer_role =>
          { :five_year_bar => false,
            :requested_coverage_start_date => Time.zone.today,
            :aasm_state => "unverified",
            :is_applicant => true,
            :birth_location => nil,
            :marital_status => nil,
            :is_active => true,
            :is_applying_coverage => true,
            :bookmark_url => nil,
            :admin_bookmark_url => nil,
            :contact_method => "Paper and Electronic communications",
            :language_preference => "English",
            :is_state_resident => true,
            :identity_validation => "na",
            :identity_update_reason => nil,
            :application_validation => "na",
            :application_update_reason => nil,
            :identity_rejected => false,
            :application_rejected => false,
            :documents => [],
            :vlp_documents =>
            [{ :subject => "I-327 (Reentry Permit)",
               :description => nil,
               :alien_number => "123456789",
               :i94_number => nil,
               :visa_number => nil,
               :passport_number => "123456",
               :sevis_id => nil,
               :naturalization_number => nil,
               :receipt_number => "abc4567890123",
               :citizenship_number => nil,
               :card_number => nil,
               :country_of_citizenship => "Ukraine",
               :expiration_date => DateTime.now,
               :issuing_country => "USA" }],
            :ridp_documents => [{ :status => "not submitted", :ridp_verification_type => "Identity", :comment => nil }],
            :verification_type_history_elements => [],
            :lawful_presence_determination =>
            { :vlp_verified_at => nil,
              :vlp_authority => nil,
              :vlp_document_id => nil,
              :citizen_status => "us_citizen",
              :citizenship_result => nil,
              :qualified_non_citizenship_result => nil,
              :aasm_state => "verification_pending",
              :ssa_responses => [],
              :ssa_requests => [],
              :vlp_responses => [],
              :vlp_requests => [] },
            :local_residency_responses => [],
            :local_residency_requests => [] },
          :resident_role => nil,
          :individual_market_transitions => [{ :role_type => "consumer", :start_on => Time.zone.today, :end_on => nil,
                                               :reason_code => "generating_consumer_role",
                                               :submitted_at => DateTime.now }],
          :verification_types =>
          [{ :type_name => "DC Residency",
             :validation_status => "unverified",
             :applied_roles => ["consumer_role"],
             :update_reason => nil,
             :rejected => nil,
             :external_service => nil,
             :due_date => Time.zone.today + 36.days,
             :due_date_type => nil,
             :inactive => nil,
             :vlp_documents => [] },
           { :type_name => "Social Security Number",
             :validation_status => "unverified",
             :applied_roles => ["consumer_role"],
             :update_reason => nil,
             :rejected => nil,
             :external_service => nil,
             :due_date => Time.zone.today + 36.days,
             :due_date_type => nil,
             :inactive => nil,
             :vlp_documents => [] },
           { :type_name => "Citizenship",
             :validation_status => "unverified",
             :applied_roles => ["consumer_role"],
             :update_reason => nil,
             :rejected => nil,
             :external_service => nil,
             :due_date => Time.zone.today + 36.days,
             :due_date_type => nil,
             :inactive => nil,
             :vlp_documents => [] }],
          :user => {},
          :addresses =>
          [{ :kind => "home", :address_1 => "1111 Awesome Street NE", :address_2 => "#111", :address_3 => "",
             :city => "Washington", :county => "Hampden", :state => "DC", :zip => "01001", :country_name => "United States of America",
             :has_fixed_address => true },
           { :kind => "home", :address_1 => "1112 Awesome Street NE", :address_2 => "#112", :address_3 => "",
             :city => "Washington", :county => "Hampden",
             :state => "DC", :zip => "01001", :country_name => "United States of America", :has_fixed_address => true }],
          :emails => [{ :kind => "home", :address => "example1@example.com" }, { :kind => "home", :address => "example2@example.com" }],
          :phones =>
          [{ :kind => "home", :country_code => "", :area_code => "202", :number => "1111111", :extension => "1",
             :primary => nil, :full_phone_number => "20211111111" },
           { :kind => "home", :country_code => "", :area_code => "202", :number => "1111112", :extension => "2", :primary => nil,
             :full_phone_number => "20211111122" }],
          :documents => [],
          :timestamp => { :created_at => DateTime.now, :modified_at => DateTime.now } },
         :timestamp => { :created_at => DateTime.now, :modified_at => DateTime.now } },
       { :hbx_id => "732021",
         :is_primary_applicant => false,
         :is_consent_applicant => false,
         :is_coverage_applicant => true,
         :is_active => true,
         :person =>
         { :person_id => "66553ea76e3a72323152ccfa",
           :external_person_link => "http://127.0.0.1:3000/exchanges/agents/resume_enrollment?person_id=66553ea76e3a72323152ccfa",
           :hbx_id => "732021",
           :person_name => { :first_name => "John", :middle_name => nil, :last_name => "Smith2", :name_sfx => nil,
                             :name_pfx => nil, :full_name => "John Smith2",
                             :alternate_name => nil },
           :person_demographics =>
           { :encrypted_ssn => nil, :no_ssn => true, :gender => "male", :dob => Time.zone.today, :date_of_death => nil,
             :dob_check => nil, :is_incarcerated => false,
             :ethnicity => nil, :race => nil, :tribal_id => nil, :language_code => "en", :alive_status => {} },
           :person_health => { :is_physically_disabled => nil, :is_tobacco_user => "unknown" },
           :no_dc_address => false,
           :no_dc_address_reason => "",
           :is_homeless => false,
           :is_temporarily_out_of_state => false,
           :age_off_excluded => false,
           :is_applying_for_assistance => nil,
           :is_active => true,
           :is_disabled => nil,
           :person_relationships => [],
           :consumer_role => nil,
           :resident_role => nil,
           :individual_market_transitions => [],
           :verification_types => [],
           :user => {},
           :addresses =>
           [{ :kind => "home", :address_1 => "1113 Awesome Street NE", :address_2 => "#113",
              :address_3 => "", :city => "Washington", :county => "Hampden", :state => "DC", :zip => "01001",
              :country_name => "United States of America", :has_fixed_address => true },
            { :kind => "home", :address_1 => "1114 Awesome Street NE", :address_2 => "#114", :address_3 => "",
              :city => "Washington", :county => "Hampden",
              :state => "DC", :zip => "01001", :country_name => "United States of America", :has_fixed_address => true }],
           :emails => [{ :kind => "home", :address => "example3@example.com" }, { :kind => "home", :address => "example4@example.com" }],
           :phones =>
           [{ :kind => "home", :country_code => "", :area_code => "202", :number => "1111113", :extension => "3",
              :primary => nil, :full_phone_number => "20211111133" },
            { :kind => "home", :country_code => "", :area_code => "202", :number => "1111114", :extension => "4", :primary => nil,
              :full_phone_number => "20211111144" }],
           :documents => [],
           :timestamp => { :created_at => DateTime.now, :modified_at => DateTime.now } },
         :timestamp => { :created_at => DateTime.now, :modified_at => DateTime.now } },
       { :hbx_id => "732022",
         :is_primary_applicant => false,
         :is_consent_applicant => false,
         :is_coverage_applicant => true,
         :is_active => true,
         :person =>
         { :person_id => "66553ea76e3a72323152cd0c",
           :external_person_link => "http://127.0.0.1:3000/exchanges/agents/resume_enrollment?person_id=66553ea76e3a72323152cd0c",
           :hbx_id => "732022",
           :person_name => { :first_name => "John", :middle_name => nil, :last_name => "Smith3",
                             :name_sfx => nil, :name_pfx => nil, :full_name => "John Smith3",
                             :alternate_name => nil },
           :person_demographics =>
           { :encrypted_ssn => nil, :no_ssn => true, :gender => "male", :dob => Time.zone.today,
             :date_of_death => nil, :dob_check => nil, :is_incarcerated => false,
             :ethnicity => nil, :race => nil, :tribal_id => nil, :language_code => "en", :alive_status => {} },
           :person_health => { :is_physically_disabled => nil, :is_tobacco_user => "unknown" },
           :no_dc_address => false,
           :no_dc_address_reason => "",
           :is_homeless => false,
           :is_temporarily_out_of_state => false,
           :age_off_excluded => false,
           :is_applying_for_assistance => nil,
           :is_active => true,
           :is_disabled => nil,
           :person_relationships => [],
           :consumer_role => nil,
           :resident_role => nil,
           :individual_market_transitions => [],
           :verification_types => [],
           :user => {},
           :addresses =>
           [{ :kind => "home", :address_1 => "1115 Awesome Street NE", :address_2 => "#115",
              :address_3 => "", :city => "Washington", :county => "Hampden", :state => "DC", :zip => "01001",
              :country_name => "United States of America", :has_fixed_address => true },
            { :kind => "home", :address_1 => "1116 Awesome Street NE", :address_2 => "#116",
              :address_3 => "", :city => "Washington", :county => "Hampden",
              :state => "DC", :zip => "01001", :country_name => "United States of America", :has_fixed_address => true }],
           :emails => [{ :kind => "home", :address => "example5@example.com" }, { :kind => "home", :address => "example6@example.com" }],
           :phones =>
           [{ :kind => "home", :country_code => "", :area_code => "202", :number => "1111115", :extension => "5",
              :primary => nil, :full_phone_number => "20211111155" },
            { :kind => "home", :country_code => "", :area_code => "202", :number => "1111116", :extension => "6", :primary => nil,
              :full_phone_number => "20211111166" }],
           :documents => [],
           :timestamp => { :created_at => DateTime.now, :modified_at => DateTime.now } },
         :timestamp => { :created_at => DateTime.now, :modified_at => DateTime.now } }],
      :renewal_consent_through_year => 2017,
      :special_enrollment_periods => [],
      :payment_transactions => [],
      :magi_medicaid_applications => [],
      :documents => [],
      :timestamp => { :created_at => DateTime.now, :modified_at => DateTime.now },
      :eligibility_determination =>
      { :effective_date => Time.zone.today,
        :subjects =>
        { "#<URI::GID gid://enroll/FamilyMember/66553ea76e3a72323152ccf0>" =>
          { :first_name => "John",
            :last_name => "Smith1",
            :hbx_id => "732020",
            :person_id => "66553ea76e3a72323152ccd4",
            :encrypted_ssn => "cb6H09SJ4Fhd3sNr0MAOVYYHuP8BKMdKlQ==\n",
            :outstanding_verification_status => "not_enrolled",
            :is_primary => true,
            :dob => Time.zone.today,
            :eligibility_states =>
            { :aptc_csr_credit => { :eligibility_item_key => "aptc_csr_credit", :determined_at => DateTime.now,
                                    :evidence_states => {} },
              :aca_individual_market_eligibility =>
              { :is_eligible => true,
                :earliest_due_date => nil,
                :document_status => "NA",
                :eligibility_item_key => "aca_individual_market_eligibility",
                :determined_at => DateTime.now,
                :evidence_states =>
                { :citizenship =>
                  { :status => :unverified,
                    :is_satisfied => true,
                    :verification_outstanding => false,
                    :due_on => nil,
                    :evidence_item_key => :citizenship,
                    :visited_at => DateTime.now,
                    :evidence_gid => "#<URI::GID gid://enroll/VerificationType/66553ea76e3a72323152cce8>" },
                  :social_security_number =>
                  { :status => :unverified,
                    :is_satisfied => true,
                    :verification_outstanding => false,
                    :due_on => nil,
                    :evidence_item_key => :social_security_number,
                    :visited_at => DateTime.now,
                    :evidence_gid => "#<URI::GID gid://enroll/VerificationType/66553ea76e3a72323152cce6>" },
                  :residency =>
                  { :status => :unverified,
                    :is_satisfied => true,
                    :verification_outstanding => false,
                    :due_on => nil,
                    :evidence_item_key => :residency,
                    :visited_at => DateTime.now,
                    :evidence_gid => "#<URI::GID gid://enroll/VerificationType/66553ea76e3a72323152cce5>" } } },
              :health_product_enrollment_status => { :eligibility_item_key => "health_product_enrollment_status", is_eligible: true,
                                                     :determined_at => DateTime.now, :evidence_states => {} },
              :dental_product_enrollment_status => { :eligibility_item_key => "dental_product_enrollment_status",
                                                     :determined_at => DateTime.now,
                                                     :evidence_states => {} } } },
          "#<URI::GID gid://enroll/FamilyMember/66553ea76e3a72323152cd09>" =>
          { :first_name => "John",
            :last_name => "Smith2",
            :hbx_id => "732021",
            :person_id => "66553ea76e3a72323152ccfa",
            :outstanding_verification_status => "not_enrolled",
            :is_primary => false,
            :dob => Time.zone.today,
            :eligibility_states =>
            { :aptc_csr_credit => { :eligibility_item_key => "aptc_csr_credit", :determined_at => DateTime.now, :evidence_states => {} },
              :aca_individual_market_eligibility => { :eligibility_item_key => "aca_individual_market_eligibility",
                                                      :determined_at => DateTime.now,
                                                      :evidence_states => {} },
              :health_product_enrollment_status => { :eligibility_item_key => "health_product_enrollment_status",
                                                     :determined_at => DateTime.now,
                                                     :evidence_states => {} },
              :dental_product_enrollment_status => { :eligibility_item_key => "dental_product_enrollment_status",
                                                     :determined_at => DateTime.now,
                                                     :evidence_states => {} } } },
          "#<URI::GID gid://enroll/FamilyMember/66553ea76e3a72323152cd1b>" =>
          { :first_name => "John",
            :last_name => "Smith3",
            :hbx_id => "732022",
            :person_id => "66553ea76e3a72323152cd0c",
            :outstanding_verification_status => "not_enrolled",
            :is_primary => false,
            :dob => Time.zone.today,
            :eligibility_states =>
            { :aptc_csr_credit => { :eligibility_item_key => "aptc_csr_credit", :determined_at => DateTime.now, :evidence_states => {} },
              :aca_individual_market_eligibility => { :eligibility_item_key => "aca_individual_market_eligibility",
                                                      :determined_at => DateTime.now,
                                                      :evidence_states => {} },
              :health_product_enrollment_status => { :eligibility_item_key => "health_product_enrollment_status",
                                                     :determined_at => DateTime.now,
                                                     :evidence_states => {} },
              :dental_product_enrollment_status => { :eligibility_item_key => "dental_product_enrollment_status",
                                                     :determined_at => DateTime.now,
                                                     :evidence_states => {} } } } },
        :outstanding_verification_status => "not_enrolled",
        :outstanding_verification_earliest_due_date => nil,
        :outstanding_verification_document_status => "NA" },
      :irs_groups => [{ :hbx_id => "", :start_on => Time.zone.today, :end_on => nil, :is_active => true }],
      :households =>
      [{ :start_date => Time.zone.today,
         :end_date => nil,
         :is_active => true,
         :irs_groups => { :hbx_id => "", :start_on => Time.zone.today, :end_on => nil, :is_active => true },
         :tax_households => [],
         :coverage_households =>
        [{ :is_immediate_family => true,
           :is_determination_split_household => false,
           :submitted_at => nil,
           :aasm_state => "applicant",
           :coverage_household_members => [{
             :family_member_reference => { :family_member_hbx_id => "732020", :first_name => "John", :last_name => "Smith1",
                                           :is_primary_family_member => true, :age => 52,
                                           :relation_with_primary => "self" }, :is_subscriber => true
           }] },
         { :is_immediate_family => false, :is_determination_split_household => false, :submitted_at => nil, :aasm_state => "applicant",
           :coverage_household_members => [] }] }] }
  end
end
