development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: crm_gateway_development

test:
  adapter: async
  url: redis://localhost:6379/1
  channel_prefix: crm_gateway_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: crm_gateway_production