default: &default
  host: sandbox-crm.cme.openhbx.org
  username: username
  password: password

development: *default
test: *default
production:
  host: <%= ENV['SUGAR_CRM_HOST'] %>
  username: <%= ENV['SUGAR_CRM_USERNAME'] %>
  password: <%= ENV['SUGAR_CRM_PASSWORD'] %>
